"""empty message

Revision ID: 8c5078d54a45
Revises: c4828c47f39c
Create Date: 2025-06-07 22:57:52.209072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5078d54a45'
down_revision = 'c4828c47f39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               nullable=True)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('eye_color',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
