"""empty message

Revision ID: c4828c47f39c
Revises: 7ccfd5618146
Create Date: 2025-06-07 18:27:58.461868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4828c47f39c'
down_revision = '7ccfd5618146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=120), nullable=False))
        batch_op.drop_column('population')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('terrain')

    # ### end Alembic commands ###
